# Generated by Django 4.2.1 on 2023-06-11 19:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_customerprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerProfile',
            new_name='Customer',
        ),
    ]
