# Generated by Django 4.2.1 on 2023-06-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('cover', models.FileField(upload_to='files/promote_covers/')),
            ],
        ),
    ]
