# Generated by Django 4.2.1 on 2023-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_promote_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('icon_class', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='promote',
            name='link',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='promote',
            name='category',
            field=models.CharField(choices=[('st', 'start'), ('pr', 'project')], default='st', max_length=64),
        ),
    ]
