# Generated by Django 4.2.1 on 2023-06-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_product_productpromote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
