# Generated by Django 4.2.1 on 2023-06-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(default='icon', max_length=128),
        ),
    ]
