# Generated by Django 4.2.1 on 2023-06-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promote',
            name='active_index',
            field=models.IntegerField(default=0),
        ),
    ]
