# Generated by Django 4.2.1 on 2023-06-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_productpromote_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='active_index',
            field=models.IntegerField(default=0),
        ),
    ]
