# Generated by Django 4.2.1 on 2023-06-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_service_active_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpromote',
            name='active_index',
            field=models.IntegerField(default=0),
        ),
    ]
